import Avatars from "../../../lib/Avatars";
export const marketingDataRobots = [
    {
      mainCard: {
        title: "Ace",
        description: "Expert in marketing strategies and competitor analysis",
        keyPoints : ['Generate detailed and actionable marketing strategies','Analyze competitors by identifying strengths, weaknesses, opportunities, and threats','Develop comprehensive product launch plans with timelines and KPIs','Craft personalized investor updates and reports'],  
        image:Avatars.Ace,
      },
      subCard1: {
        title: "Cora",
        description: "Your executive assistant, on AI.", 
        keyPoints : ['Provide instant responses to customer queries via chat and email',
'Create FAQ sections, user manuals, and troubleshooting guides',
'Analyze customer feedback to generate actionable support improvement reports'],  
        image: Avatars.Cora,
      },
      subCard2: {
        title: "Echo",
        description: "Optimizes online stores for maximum performance", 
        keyPoints : ['Write high-converting product descriptions and design engaging landing pages',
          'Perform store audits and recommend optimization strategies',
          'Identify winning product ideas and calculate profit margins'], 
        image: Avatars.Echo,
      },
    },
    {
      mainCard: {
        title: "Delta",
        description: "Transforms raw data into actionable insights", 
        keyPoints : ['Generate balance sheets, profit/loss statements, and other financial reports',
          'Forecast future sales trends and revenue streams based on current data',
          'Calculate ROI for projects and offer actionable insights'], 
        image: Avatars.Delta,
      },
      subCard1: {
        title: "Ember",
        description: "Creates engaging email campaigns that convert", 
        keyPoints:['Automate the creation of email campaigns, calendars, and workflows',
          'Design emails for abandoned carts, customer win-backs, and special promotions',
          'Provide post-purchase email flows that boost customer satisfaction'],
        image: Avatars.Ember,
      },
      subCard2: {
        title: "Maverick",
        description: "Expert in sales strategies and customer acquisition", 
        keyPoints:['Generate persuasive cold email scripts and follow-ups',
          'Create legally sound sales contracts and comprehensive incentive plans',
          'Provide expert negotiation guidance and discovery call frameworks'],
        image: Avatars.Maverik,
      },
       },
  
    // {
    //   mainCard: {
    //     title: "Gala",
    //     description: "Your personal coach for growth and development", 
    //     keyPoints:['Develop personalized meal and workout plans',
    //       'Assist with studying through optimized schedules and study aids',
    //      ' Offer productivity recommendations for daily and weekly tasks'],
    //     image: "/images/Avatars/Avatar7.png",
    //   },
    //   subCard1: {
    //     title: "Quill",
    //     description: "Crafts compelling content that engages and converts", 
    //     keyPoints:['Write engaging ad copy, blogs, newsletters, and social media posts',
    //       'Optimize scripts for Facebook ads, video sales letters (VSL), and advertorials',
    //       'Enhance written content for readability, SEO, and conversions'],
    //     image: "/images/Avatars/Avatar8.png",
    //   },
    //   subCard2: {
    //     title: "Ryder",
    //     description: "Finds and retains top talent for your organization", 
    //     keyPoints:['Screen resumes with tailored filters for role-specific qualifications',
    //       'Develop personalized onboarding plans for new hires',
    //       'Generate outreach emails and job descriptions to attract talent'],
    //     image: "/images/Avatars/Avatar10.png",
    //   },
    //   bgClr: "#1377ba",
    // }, 
    // {
    //   mainCard: {
    //     title: "Sage",
    //     description: "Boosts your online presence with effective SEO strategies", 
    //     keyPoints:['Write SEO-optimized blogs to improve website visibility',
    //       'Audit websites for SEO performance and recommend improvements',
    //       'Provide keyword strategies to improve search engine rankings'],
    //     image: "/images/Avatars/Avatar11.png",
    //   },
    //   subCard1: {
    //     title: "Lumen",
    //     description: "Maximizes your social media impact", 
    //     keyPoints:['Create consistent and engaging content calendars',
    //       'Develop scripts for TikTok, YouTube, and Instagram Reels',
    //       'Identify viral trends to boost brand visibility'],
    //     image: "/images/Avatars/Avatar6.png",
    //   },
    //   subCard2: {
    //     title: "Vera",
    //     description: "Supports your daily tasks with efficiency", 
    //     keyPoints:['Manage tasks like trip planning and financial reporting',
    //       'Organize events such as birthdays and business meetings',
    //       'Provide administrative support for projects and workflows'],
    //     image: "/images/Avatars/Avatar13.png",
    //   },
    //   bgClr: "#1377ba",
    // }, 
    // {
    //   mainCard: {
    //     title: "Aria",
    //     description: "Enhances learning experiences with tailored plans", 
    //     keyPoints:['Create personalized learning plans for all skill levels',
    //       'Summarize study materials into concise notes and quizzes',
    //       'Recommend resources for academic and personal growth'],
    //     image: "/images/Avatars/Avatar14.png",
    //   },
    //   subCard1: {
    //     title: "Drift",
    //     description: "Plans memorable events with precision", 
    //     keyPoints:['Plan corporate and social events with detailed schedules',
    //       'Recommend activities, catering options, and decor ideas',
    //       'Manage RSVPs and analyze post-event feedback'],
    //     image: "/images/Avatars/Avatar15.png",
    //   },
    //   subCard2: {
    //     title: "Neon",
    //     description: "Transforms ideas into stunning visuals", 
    //     keyPoints:['Design templates for presentations and brochures',
    //       'Suggest branding elements like logos and typography',
    //       'Provide ideas for visual storytelling and impactful designs'],
    //     image: "/images/Avatars/Avatar10.png",
    //   },
    //   bgClr: "#1377ba",
    // },
  ];
  