import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '@descope/nextjs-sdk';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider projectId="P2rKjIaILiYkDRu8bST9CS14pS3P">
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
    </AuthProvider>
  );
}


