import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@descope/nextjs-sdk";
import { ApolloProvider } from "@/providers/ApolloPovider";
import StoreProvider from "@/providers/StoreProvider";
import { Playfair_Display } from '@next/font/google'; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playwriteFont = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'], // Adjust as per need
  variable: '--font-playwrite', // Optional CSS variable
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <AuthProvider projectId={process.env.DESCOPE_PROJECT_ID as string}>
            <ApolloProvider>{children}</ApolloProvider>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
