import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '@descope/nextjs-sdk';
import { ApolloProvider } from "@/providers/ApolloPovider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider projectId={process.env.DESCOPE_PROJECT_ID as string}>
      <ApolloProvider>
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
    </ApolloProvider>
    </AuthProvider>
  );
}


